// Code generated by hand for gomock-style expectations. DO NOT EDIT.
package mocks

import (
	"reflect"

	"github.com/golang/mock/gomock"
	"github.com/labstack/echo/v4"

	sqldb "immortal-architecture-bad-api/backend/internal/db/sqlc"
	openapi "immortal-architecture-bad-api/backend/internal/generated/openapi"
	"immortal-architecture-bad-api/backend/internal/service"
)

// MockTemplateServicer is a mock of service.TemplateServicer.
type MockTemplateServicer struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateServicerMockRecorder
}

// MockTemplateServicerMockRecorder records invocations on MockTemplateServicer.
type MockTemplateServicerMockRecorder struct {
	mock *MockTemplateServicer
}

// NewMockTemplateServicer creates a new gomock mock for TemplateServicer.
func NewMockTemplateServicer(ctrl *gomock.Controller) *MockTemplateServicer {
	mock := &MockTemplateServicer{ctrl: ctrl}
	mock.recorder = &MockTemplateServicerMockRecorder{mock}
	return mock
}

// EXPECT exposes the recorder for expectation declarations.
func (m *MockTemplateServicer) EXPECT() *MockTemplateServicerMockRecorder {
	return m.recorder
}

// ListTemplates mocks the corresponding TemplateServicer method.
func (m *MockTemplateServicer) ListTemplates(ctx echo.Context, filters service.TemplateFilters) ([]*openapi.ModelsTemplateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplates", ctx, filters)
	ret0, _ := ret[0].([]*openapi.ModelsTemplateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplates indicates an expected call of ListTemplates.
func (mr *MockTemplateServicerMockRecorder) ListTemplates(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockTemplateServicer)(nil).ListTemplates), ctx, filters)
}

// CreateTemplate mocks the corresponding TemplateServicer method.
func (m *MockTemplateServicer) CreateTemplate(ctx echo.Context, ownerID string, name string, fields []sqldb.Field) (*openapi.ModelsTemplateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, ownerID, name, fields)
	ret0, _ := ret[0].(*openapi.ModelsTemplateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockTemplateServicerMockRecorder) CreateTemplate(ctx, ownerID, name, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockTemplateServicer)(nil).CreateTemplate), ctx, ownerID, name, fields)
}

// DeleteTemplate mocks the corresponding TemplateServicer method.
func (m *MockTemplateServicer) DeleteTemplate(ctx echo.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockTemplateServicerMockRecorder) DeleteTemplate(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockTemplateServicer)(nil).DeleteTemplate), ctx, id)
}

// GetTemplate mocks the corresponding TemplateServicer method.
func (m *MockTemplateServicer) GetTemplate(ctx echo.Context, id string) (*openapi.ModelsTemplateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", ctx, id)
	ret0, _ := ret[0].(*openapi.ModelsTemplateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockTemplateServicerMockRecorder) GetTemplate(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockTemplateServicer)(nil).GetTemplate), ctx, id)
}

// UpdateTemplate mocks the corresponding TemplateServicer method.
func (m *MockTemplateServicer) UpdateTemplate(ctx echo.Context, id string, name string, fields []openapi.ModelsUpdateFieldRequest) (*openapi.ModelsTemplateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, id, name, fields)
	ret0, _ := ret[0].(*openapi.ModelsTemplateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockTemplateServicerMockRecorder) UpdateTemplate(ctx, id, name, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockTemplateServicer)(nil).UpdateTemplate), ctx, id, name, fields)
}
