// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: accounts.sql

package sqldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, first_name, last_name, is_active, provider, provider_account_id, thumbnail, last_login_at, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (*Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Thumbnail,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAccountByProvider = `-- name: GetAccountByProvider :one
SELECT id, email, first_name, last_name, is_active, provider, provider_account_id, thumbnail, last_login_at, created_at, updated_at
FROM accounts
WHERE provider = $1
  AND provider_account_id = $2
`

type GetAccountByProviderParams struct {
	Provider          string `db:"provider" json:"provider"`
	ProviderAccountID string `db:"provider_account_id" json:"provider_account_id"`
}

func (q *Queries) GetAccountByProvider(ctx context.Context, arg *GetAccountByProviderParams) (*Account, error) {
	row := q.db.QueryRow(ctx, getAccountByProvider, arg.Provider, arg.ProviderAccountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Thumbnail,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertAccount = `-- name: UpsertAccount :one
INSERT INTO accounts (
    email,
    first_name,
    last_name,
    provider,
    provider_account_id,
    thumbnail,
    last_login_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider, provider_account_id)
DO UPDATE SET
    email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    thumbnail = EXCLUDED.thumbnail,
    last_login_at = EXCLUDED.last_login_at,
    updated_at = NOW()
RETURNING id, email, first_name, last_name, is_active, provider, provider_account_id, thumbnail, last_login_at, created_at, updated_at
`

type UpsertAccountParams struct {
	Email             string             `db:"email" json:"email"`
	FirstName         string             `db:"first_name" json:"first_name"`
	LastName          string             `db:"last_name" json:"last_name"`
	Provider          string             `db:"provider" json:"provider"`
	ProviderAccountID string             `db:"provider_account_id" json:"provider_account_id"`
	Thumbnail         pgtype.Text        `db:"thumbnail" json:"thumbnail"`
	LastLoginAt       pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg *UpsertAccountParams) (*Account, error) {
	row := q.db.QueryRow(ctx, upsertAccount,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Provider,
		arg.ProviderAccountID,
		arg.Thumbnail,
		arg.LastLoginAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Thumbnail,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
