// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Email             string             `db:"email" json:"email"`
	FirstName         string             `db:"first_name" json:"first_name"`
	LastName          string             `db:"last_name" json:"last_name"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	Provider          string             `db:"provider" json:"provider"`
	ProviderAccountID string             `db:"provider_account_id" json:"provider_account_id"`
	Thumbnail         pgtype.Text        `db:"thumbnail" json:"thumbnail"`
	LastLoginAt       pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Field struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	TemplateID pgtype.UUID `db:"template_id" json:"template_id"`
	Label      string      `db:"label" json:"label"`
	Order      int32       `db:"order" json:"order"`
	IsRequired bool        `db:"is_required" json:"is_required"`
}

type Note struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Title      string             `db:"title" json:"title"`
	TemplateID pgtype.UUID        `db:"template_id" json:"template_id"`
	OwnerID    pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Status     string             `db:"status" json:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Section struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	NoteID  pgtype.UUID `db:"note_id" json:"note_id"`
	FieldID pgtype.UUID `db:"field_id" json:"field_id"`
	Content string      `db:"content" json:"content"`
}

type Template struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	OwnerID   pgtype.UUID        `db:"owner_id" json:"owner_id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
